tools/output-states: Add missing include <locale.h>
Fails to build with clang on musl libc:

	../tools/phoc-outputs-states.c:131:3: error: call to undeclared function 'setlocale'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
	  131 |   setlocale (LC_MESSAGES, "");
	      |   ^
	../tools/phoc-outputs-states.c:131:14: error: use of undeclared identifier 'LC_MESSAGES'
	  131 |   setlocale (LC_MESSAGES, "");
	      |              ^
	2 errors generated.

Signed-off-by: Achill Gilgenast <achill@achill.org>
Part-of: <https://gitlab.gnome.org/World/Phosh/phoc/-/merge_requests/707>